# dispara um evento quando acontece um novo push na master.
name: Dispatch Commit

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v1
        with:
          token: "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"
          repository: "https://github.com/MEDGRUPOGIT/med-components"
          event-type: new-commit
