# cria uma branch de sync quando um commit ocorre na master
name: Dispatch Commit

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://fbalbinoribeiro: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@github.com/MEDGRUPOGIT/ionic-framework.git"
          source_branch: "master"
          destination_repo: "https://fbalbinoribeiro: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@github.com/MEDGRUPOGIT/med-components.git"
          destination_branch: "sync"
