# dispara um evento quando acontece um novo push na master.
name: Dispatch Commit

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ secrets.REPO_ACCESS_TOKEN }}
      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: MEDGRUPOGIT/med-components
          event-type: new-commit
