# cria uma branch de sync quando um commit ocorre na master
name: Dispatch Commit

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "MEDGRUPOGIT/ionic-framework"
          source_branch: "master"
          destination_repo: "MEDGRUPOGIT/med-components"
          destination_branch: "sync"
